title: Teaching At The Frontline
baseline: .
description: My journey into Pakistan's Education System
baseurl: /
canonicalurl: true
theme: hyde
date:
  format: j F Y
  timezone: Europe/Paris
pagination:
  max: 5
  path: /pages
output:
  formats:
    netlify_redirects:
      extension: ''
      mediatype: text/plain
virtualpages:
  _redirects:
    output: netlify_redirects
  admin:
    layout: admin/index
    title: Content Manager (Netlify CMS)
    output: html
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
